const CONSTS = {
  PROVIDER_ID: 'react-circumstance-provider',
  EVENTS: {
    HIDE_ALL: 'HIDE_ALL'
  },
  RENDER_BUFFER: 0
}

export enum CIRCUMSTANCE_TYPES {
  CIRCUMSTANCE_MENU = 'CIRCUMSTANCE_MENU',
  CIRCUMSTANCE_SUBMENU = 'CIRCUMSTANCE_SUBMENU',
  CIRCUMSTANCE_MENUITEM = 'CIRCUMSTANCE_MENUITEM',
  CIRCUMSTANCE_DIVIDER = 'CIRCUMSTANCE_DIVIDER',
  CIRCUMSTANCE_DEFAULT = 'CIRCUMSTANCE_DEFAULT'
}

export default CONSTS
